export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT"

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"

export const ADD_PRODUCT_WITH_TEXT_CART = "ADD_PRODUCT_WITH_TEXT_CART"

export const UPDATE_PRODUCT_WITH_TEXT_CART = "UPDATE_PRODUCT_WITH_TEXT_CART"

export const DELETE_PRODUCT_WITH_TEXT_CART = "DELETE_PRODUCT_WITH_TEXT_CART"

export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";

export const GET_PRODUCTS_ON_CATEGORY = "GET_PRODUCTS_ON_CATEGORY";

// Login and Register
export const GET_LOGIN_WITH_USER = "GET_LOGIN_WITH_USER";

export const ADD_REGISTER_WITH_USER = "ADD_REGISTER_WITH_USER";
